services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data


  greenhouse:
    image: greenhouse:latest
    build: .
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres

volumes:
  pg-data:
